[workspace]
members = ["src/rust"]

[patch.crates-io]
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "cebf5259" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "a61b6df" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "4aabfbf" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "4aabfbf" }
